ex.3.1. Трансформировать массив объектов в массив имён
js-tasks-ru/jsbasic-20201022_gorin-valeriy-aleksandrovich pull request #4
Opened 2020-11-07 10:38 UTC by ziktapurik

2020-11-07 10:45 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Трансформировать в массив имён
+ должна преобразовать users в массив имён
```

Добавляю преподавателя (@koalex) для код-ревью, посмотрим что он скажет :)

2020-11-07 11:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-11-07 13:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-11-08 08:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-11-08 22:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-11-14 15:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-11-14 16:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-11-14 19:04 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-11-14 19:11 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Функция highlight
+ Проставит класс male/female, в зависимости от содержимого ячекйки Gender
+ Проставит аттрибут hidden, если  data-available атрибута нет вообще
+ Установит inline-стиль style="text-decoration: line-through", если значение ячейки Age меньше 18
+ Проставит класс available/unavailable, в зависимости от значения атрибута data-available у ячейки Status
```
```diff
Фильтрация по диапазону
+ должна фильтровать диапазон
+ не должна менять исходный массив
```
```diff
Трансформировать в массив имён
+ должна преобразовать users в массив имён
```
```diff
Найти min/max в строке
+ 25,-1,-234,4,   1000
+ 1, -5.8 или 10, хотя 34 + -5.3 и 73
```
```diff
Функция makeFriendsList(friends)
+ проверяем содержимое списка
+ функция должна возвращать HTML список
+ Число элементов в списке и число объектов в массиве должны быть одинаковыми
```
```diff
Спрятать себя
- после клика по кнопке она должна исчезнуть
```
```diff
Функция showSalary(users, age)
+ для пользователей до 30 лет должна вывести строку с зарплатами
+ для пользователей до 40 лет должна вывести строку с зарплатами
```
```diff
Выделите ячейки по диагонали
+ должна окрашивать ячейку четвёртой строки в красный
+ должна окрашивать ячейку третьей строки в красный
+ должна окрашивать ячейку пятой строки в красный
+ должна окрашивать ячейку второй строки в красный
+ должна окрашивать ячейку первой строки в красный
```

2020-11-21 13:03 UTC, koalex requested changes
Не проходят тесты. Исправь.

2020-11-22 08:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-11-22 08:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-11-22 15:41 UTC, koalex approved these changes

2020-11-22 15:42 UTC, merged